name: firebase_setup
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.8.0
  firebase_storage: ^11.2.6
  provider: ^6.0.5
  material_symbols_icons: ^4.2668.0
  eva_icons_flutter: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/love2.png
    - assets/newws.png
